apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: web-app
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 30000
    targetPort: 8080
  selector:
    app: web-app