apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-pvcf
        persistentVolumeClaim:
          claimName: mysql-pvcf
      containers:
      - name: mysql
        image: 772859080303.dkr.ecr.us-east-1.amazonaws.com/assignment_mysql:mysql
        volumeMounts:
        - name: mysql-pvcf
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
        env:
          - name: DBPWD
            valueFrom:
              secretKeyRef:
                name: db-user-pass-mspwd
                key: DBPWD
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                name: db-user-pass-mspwd
                key: DBUSER
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass-mspwd
                key: MYSQL_ROOT_PASSWORD