apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvcf
  labels: 
    name: mysql-pvcf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 4Gi