apiVersion: v1
kind: PersistentVolume

metadata:
  name: mysql-s-pv
spec:
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/mysql
